#+Title: My configuration for emacs
#+LaTeX_CLASS: org-article
#+LaTeX_HEADER:\author{Brice Ozeene}
#+OPTIONS: toc:t

* TODO  :noexport:
C-c C-a latex

markdown polymode

* Installation

Download all files and put them in a directory called *emacs-config*.

Place this directory in the folder containing the *.emacs* file (=~/.= when doing C-x C-f).

Copy the following code at the begining of the .emacs file:
#+BEGIN_SRC emacs-lisp :export code :eval ever
;;; load automatic config
(setq user-full-name "my name")
(setq path-emacs-config "~/emacs-config")

(load-file (expand-file-name "step1-load-packages.el" path-emacs-config))
(load-file (expand-file-name "step2-general-settings.el" path-emacs-config)) 
;;(load-file (expand-file-name "step3-email.el" path-emacs-config))
(load-file (expand-file-name "step4a-ess.el" path-emacs-config)) 
(load-file (expand-file-name "step4b-orgmode.el" path-emacs-config))
(load-file (expand-file-name "step4c-other-software.el" path-emacs-config))
(load-file (expand-file-name "step5-org-class.el" path-emacs-config))
(load-file (expand-file-name "step6-org-templates.el" path-emacs-config))
(load-file (expand-file-name "step7-header.el" path-emacs-config))
(load-file (expand-file-name "step8-folding.el" path-emacs-config))
(load-file (expand-file-name "step9-spellChecking.el" path-emacs-config))

(load-file (expand-file-name "FCT-dired.el" path-emacs-config))
(load-file (expand-file-name "FCT-editing.el" path-emacs-config))
(load-file (expand-file-name "FCT-file-management.el" path-emacs-config))
(load-file (expand-file-name "FCT-R.el" path-emacs-config))
(load-file (expand-file-name "FCT-org.el" path-emacs-config))
(load-file (expand-file-name "FCT-switch-to-OS-explorer.el" path-emacs-config))
(load-file (expand-file-name "FCT-superman.el" path-emacs-config))

(load-file (expand-file-name "step10-shorcuts.el" path-emacs-config))
#+END_SRC
In the first line, replace ="my name"= by your name.

In the second line, check that ="~/emacs-config"= is where you have put emacs-config.

Install the packages that are not automatically downloaded
when launching emacs (see section dependencies below).

[Optional] Add the following lines
#+BEGIN_SRC emacs-lisp :export code :eval ever
;;; Font size
(set-face-attribute 'default nil :height 120)

;;; file at startup
(setq inhibit-startup-screen t) ;; dismiss startup screen
(find-file "~/todo.org")

(setq
 user-mail-address "myname@xxx.com"
 user-full-name  "my name"
 mu4e-compose-signature
 (concat
  "my name\n"
  "myname@xxx.com\n")
 )
#+END_SRC

* Key binding
See the file extendedCommands.org

* Dependencies

=require=:
- *install packages*: package, use-package
- *C++ mode*: cc-mode
- *dired*: dired-x, dired-quick-sort
- *email*: mu4e

=usep-package=:
- *general display*: moe-theme, powerline
- *multicolor parentheses* , rainbow-delimiters
- *scrolling*: scroll-restore
- *buffer*: ido, ido-completing-read+
- *windows*: transpose-frame
- *add header in files*: header2, header2-snps
- *restaure from previous session*: recentf
- *dired*: dired-hacks-utils, dired-sort, dired-narrow, dired-rainbow
- *shortcut*: yasnippet, auto-yasnippet
- *completion*: auto-complete, popup-complete, auto-complete-config, ac-R, hippie-exp
- *R softwre*: ess-site, ess-edit
- *bibliography*: gscholar-bibtex
- *version control*: magit, magithub
- *orgmode*: org, org-bookmark-heading, org-capture, org-agenda, org-clock, org-latex, ox-latex, ox-beamer
- *stan*: stan-mode, stan-snippets
- *putty*: tramp

* Credit

A major part of configuration comes from [[https://github.com/tagteam/emacs-genome][emacs-genome]] (thanks
thomas!!!). In particular all the functions contained in the file
=FCT-superman.el= are directly copied from emacs-genome.
