;; (add-to-list
;;  'org-structure-template-alist
;;       '(
;; 	;; ("a" . "export ascii\n")
;; 	;; ("c" . "center\n")
;; 	;; ("C" . "comment\n")
;; 	;; ("e" . "example\n")
;; 	;; ("E" . "export")
;; 	;; ("h" . "export html\n")
;; 	("L" . "export latex\n")
;; 	("leq" . "export latex\n\\begin{align*}\n\n\\end{align*}")
;; 	("Rh" . "R :results output raw drawer  :exports none :session *R* :cache no")
;; 	("Re" . "R :exports both :results output :session *R* :cache no")
;; 	("Rl" . "R :exports both :results latex :session *R* :cache no")
;; 	("Rg" . "R :results graphics :file %file :exports results :session *R* :cache no")
;; 	;; ("s" . "src")
;; 	;; ("v" . "verse\n")
;; 	))
(setq org-structure-template-alist
  '(("a" . "export ascii")
    ("c" . "center")
    ("C" . "comment")
    ("e" . "example")
    ("E" . "export")
    ("h" . "export html")
    ("l" . "export latex")
    ("leq" . "export latex\n\\begin{align*}\n\n\\end{align*}")
    ("r" . "src R :session *R* :cache no")
    ("rh" . "src R :results output raw drawer  :exports none :session *R* :cache no")
    ("re" . "src R :exports both :results output :session *R* :cache no")
    ("rl" . "src R :exports both :results latex :session *R* :cache no")
    ("rg" . "src R :results graphics :file %file :exports results :session *R* :cache no")
    ("q" . "quote\n")
    ("s" . "src")
    ("v" . "verse\n")))
